// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScreenSound.Banco;

#nullable disable

namespace ScreenSound.Shared.Dados.Migrations
{
    [DbContext(typeof(ScreenSoundContext))]
    [Migration("20260227162800_vaicaraiopeloamor")]
    partial class vaicaraiopeloamor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ScreenSound.Modelos.Artista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FotoPerfil")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Artistas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Foo Fighters é uma banda de rock alternativo americana formada por Dave Grohl em 1995.",
                            FotoPerfil = "Foto_001.png",
                            Nome = "Foo Fighters"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Queen foi uma banda de rock britânica formada em Londres em 1970.",
                            FotoPerfil = "Foto_002.png",
                            Nome = "Queen"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Led Zeppelin foi uma banda de rock britânica formada em Londres em 1968.",
                            FotoPerfil = "Foto_003.png",
                            Nome = "Led Zeppelin"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Taylor Alison Swift é uma cantora e compositora americana.",
                            FotoPerfil = "Foto_004.png",
                            Nome = "Taylor Swift"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Michael Joseph Jackson foi um cantor, compositor e dançarino americano.",
                            FotoPerfil = "Foto_005.png",
                            Nome = "Michael Jackson"
                        },
                        new
                        {
                            Id = 6,
                            Bio = "Madonna Louise Ciccone é uma cantora, compositora, atriz e empresária americana.",
                            FotoPerfil = "Foto_006.png",
                            Nome = "Madonna"
                        },
                        new
                        {
                            Id = 7,
                            Bio = "Djavan Caetano Viana é um cantor, compositor, arranjador, produtor musical, empresário, violonista e ex-futebolista brasileiro.",
                            FotoPerfil = "Foto_007.png",
                            Nome = "Djavan"
                        },
                        new
                        {
                            Id = 8,
                            Bio = "Gilberto Passos Gil Moreira é um cantor, compositor, multi-instrumentista, produtor musical, político e escritor brasileiro.",
                            FotoPerfil = "Foto_008.png",
                            Nome = "Gilberto Gil"
                        },
                        new
                        {
                            Id = 9,
                            Bio = "Caetano Emanuel Viana Telles Veloso é um cantor, compositor, violonista, escritor e produtor musical brasileiro.",
                            FotoPerfil = "Foto_009.png",
                            Nome = "Caetano Veloso"
                        });
                });

            modelBuilder.Entity("ScreenSound.Modelos.Musica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnoLancamento")
                        .HasColumnType("int");

                    b.Property<int?>("ArtistaId")
                        .HasColumnType("int");

                    b.Property<int?>("GeneroId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ArtistaId");

                    b.HasIndex("GeneroId");

                    b.ToTable("Musicas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnoLancamento = 1997,
                            ArtistaId = 1,
                            GeneroId = 1,
                            Nome = "Everlong"
                        },
                        new
                        {
                            Id = 2,
                            AnoLancamento = 2007,
                            ArtistaId = 1,
                            GeneroId = 1,
                            Nome = "The Pretender"
                        },
                        new
                        {
                            Id = 3,
                            AnoLancamento = 1999,
                            ArtistaId = 1,
                            GeneroId = 1,
                            Nome = "Learn to Fly"
                        },
                        new
                        {
                            Id = 4,
                            AnoLancamento = 1975,
                            ArtistaId = 2,
                            GeneroId = 1,
                            Nome = "Bohemian Rhapsody"
                        },
                        new
                        {
                            Id = 5,
                            AnoLancamento = 1978,
                            ArtistaId = 2,
                            GeneroId = 1,
                            Nome = "Don't Stop Me Now"
                        },
                        new
                        {
                            Id = 6,
                            AnoLancamento = 1977,
                            ArtistaId = 2,
                            GeneroId = 1,
                            Nome = "We Will Rock You"
                        },
                        new
                        {
                            Id = 7,
                            AnoLancamento = 1971,
                            ArtistaId = 3,
                            GeneroId = 1,
                            Nome = "Stairway to Heaven"
                        },
                        new
                        {
                            Id = 8,
                            AnoLancamento = 1969,
                            ArtistaId = 3,
                            GeneroId = 1,
                            Nome = "Whole Lotta Love"
                        },
                        new
                        {
                            Id = 9,
                            AnoLancamento = 1971,
                            ArtistaId = 3,
                            GeneroId = 1,
                            Nome = "Black Dog"
                        },
                        new
                        {
                            Id = 10,
                            AnoLancamento = 2014,
                            ArtistaId = 4,
                            GeneroId = 2,
                            Nome = "Blank Space"
                        },
                        new
                        {
                            Id = 11,
                            AnoLancamento = 2014,
                            ArtistaId = 4,
                            GeneroId = 2,
                            Nome = "Shake It Off"
                        },
                        new
                        {
                            Id = 12,
                            AnoLancamento = 2008,
                            ArtistaId = 4,
                            GeneroId = 2,
                            Nome = "Love Story"
                        },
                        new
                        {
                            Id = 13,
                            AnoLancamento = 1982,
                            ArtistaId = 5,
                            GeneroId = 2,
                            Nome = "Billie Jean"
                        },
                        new
                        {
                            Id = 14,
                            AnoLancamento = 1982,
                            ArtistaId = 5,
                            GeneroId = 2,
                            Nome = "Thriller"
                        },
                        new
                        {
                            Id = 15,
                            AnoLancamento = 1982,
                            ArtistaId = 5,
                            GeneroId = 2,
                            Nome = "Beat It"
                        },
                        new
                        {
                            Id = 16,
                            AnoLancamento = 1984,
                            ArtistaId = 6,
                            GeneroId = 2,
                            Nome = "Like a Virgin"
                        },
                        new
                        {
                            Id = 17,
                            AnoLancamento = 1984,
                            ArtistaId = 6,
                            GeneroId = 2,
                            Nome = "Material Girl"
                        },
                        new
                        {
                            Id = 18,
                            AnoLancamento = 1990,
                            ArtistaId = 6,
                            GeneroId = 2,
                            Nome = "Vogue"
                        },
                        new
                        {
                            Id = 19,
                            AnoLancamento = 1989,
                            ArtistaId = 7,
                            GeneroId = 3,
                            Nome = "Oceano"
                        },
                        new
                        {
                            Id = 20,
                            AnoLancamento = 1976,
                            ArtistaId = 7,
                            GeneroId = 3,
                            Nome = "Flor de Lis"
                        },
                        new
                        {
                            Id = 21,
                            AnoLancamento = 1982,
                            ArtistaId = 7,
                            GeneroId = 3,
                            Nome = "Samurai"
                        },
                        new
                        {
                            Id = 22,
                            AnoLancamento = 1982,
                            ArtistaId = 8,
                            GeneroId = 3,
                            Nome = "Andar com Fé"
                        },
                        new
                        {
                            Id = 23,
                            AnoLancamento = 1982,
                            ArtistaId = 8,
                            GeneroId = 3,
                            Nome = "Drão"
                        },
                        new
                        {
                            Id = 24,
                            AnoLancamento = 1972,
                            ArtistaId = 8,
                            GeneroId = 3,
                            Nome = "Expresso 2222"
                        },
                        new
                        {
                            Id = 25,
                            AnoLancamento = 1977,
                            ArtistaId = 9,
                            GeneroId = 3,
                            Nome = "O Leãozinho"
                        },
                        new
                        {
                            Id = 26,
                            AnoLancamento = 1978,
                            ArtistaId = 9,
                            GeneroId = 3,
                            Nome = "Sampa"
                        },
                        new
                        {
                            Id = 27,
                            AnoLancamento = 1979,
                            ArtistaId = 9,
                            GeneroId = 3,
                            Nome = "Cajuína"
                        });
                });

            modelBuilder.Entity("ScreenSound.Shared.Modelos.Modelos.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Gênero musical que se desenvolveu a partir do rock and roll nas décadas de 1950 e 1960.",
                            Nome = "Rock"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Gênero de música popular que se originou em sua forma moderna em meados da década de 1950 nos Estados Unidos e Reino Unido.",
                            Nome = "Pop"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "A Música Popular Brasileira é um gênero musical que surgiu no Brasil em meados dos anos 1960.",
                            Nome = "MPB"
                        });
                });

            modelBuilder.Entity("ScreenSound.Modelos.Musica", b =>
                {
                    b.HasOne("ScreenSound.Modelos.Artista", "Artista")
                        .WithMany("Musicas")
                        .HasForeignKey("ArtistaId");

                    b.HasOne("ScreenSound.Shared.Modelos.Modelos.Genero", "Genero")
                        .WithMany("Musicas")
                        .HasForeignKey("GeneroId");

                    b.Navigation("Artista");

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("ScreenSound.Modelos.Artista", b =>
                {
                    b.Navigation("Musicas");
                });

            modelBuilder.Entity("ScreenSound.Shared.Modelos.Modelos.Genero", b =>
                {
                    b.Navigation("Musicas");
                });
#pragma warning restore 612, 618
        }
    }
}
